version: "3"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: docker/Dockerfile
        image: task-laravel
        container_name: task-laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - task_laravel_networks

    database:
        image: mysql:8
        container_name: "database"
        environment:
            - "MYSQL_ROOT_PASSWORD=Password1"
            - "MYSQL_DATABASE=laravel_task_docker"
            - "MYSQL_USER=laravel1"
            - "MYSQL_PASSWORD=root"
        ports:
            - "3306:3306"
#        volumes:
#            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - task_laravel_networks

    nginx:
        image: nginx:alpine
        container_name: task-laravel-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - task_laravel_networks

networks:
    task_laravel_networks:
        driver: bridge
